// Code generated by "stringer -type Kind -linecomment"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindInvalid-0]
	_ = x[KindFile-1]
	_ = x[KindVarStatement-2]
	_ = x[KindIdent-3]
	_ = x[KindTextLiteral-4]
	_ = x[KindInterp-5]
	_ = x[KindPrompt-6]
}

const _Kind_name = "InvalidFileVarStatementIdentTextLiteralInterpPrompt"

var _Kind_index = [...]uint8{0, 7, 11, 23, 28, 39, 45, 51}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
