// Code generated by "stringer -type Kind -linecomment"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindInvalid-0]
	_ = x[KindFile-1]
	_ = x[KindVarStatement-2]
	_ = x[KindIdent-3]
	_ = x[KindTextLiteral-4]
	_ = x[KindURL-5]
	_ = x[KindInterp-6]
	_ = x[KindPrompt-7]
	_ = x[KindRequest-8]
	_ = x[KindComment-9]
	_ = x[KindMethod-10]
	_ = x[KindHeader-11]
	_ = x[KindInterpolatedExpression-12]
	_ = x[KindBody-13]
	_ = x[KindBodyFile-14]
	_ = x[KindResponseRedirect-15]
	_ = x[KindResponseReference-16]
	_ = x[KindHTTPVersion-17]
}

const _Kind_name = "InvalidFileVarStatementIdentTextLiteralURLInterpPromptRequestCommentMethodHeaderInterpolatedExpressionBodyBodyFileResponseRedirectResponseReferenceHTTPVersion"

var _Kind_index = [...]uint8{0, 7, 11, 23, 28, 39, 42, 48, 54, 61, 68, 74, 80, 102, 106, 114, 130, 147, 158}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
