# Changes here will be overwritten by Copier
_commit: v0.50.0
_src_path: gh:FollowTheProcess/go-template
author_email: me@followtheprocess.codes
author_name: Tom Fleet
dependency_bot: renovate
description: A command line .http file toolkit
github_url: https://github.com/FollowTheProcess/zap
github_username: FollowTheProcess
license: Apache-2.0
linter: golangci-lint
module_path: go.followtheprocess.codes/zap
project_name: Zap
project_slug: zap
project_type: binary
