version: 2

project_name: zap

before:
  hooks:
    - go mod tidy

gomod:
  proxy: true

report_sizes: true

builds:
  - id: zap
    dir: "."
    main: "./cmd/zap"
    binary: zap
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X go.followtheprocess.codes/zap/internal/cmd.version={{.Version}}
      - -X go.followtheprocess.codes/zap/internal/cmd.commit={{.Commit}}
      - -X go.followtheprocess.codes/zap/internal/cmd.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm

homebrew_casks:
  - name: zap
    binaries:
      - zap
    directory: Casks
    description: A command line .http file toolkit
    homepage: https://github.com/FollowTheProcess/zap
    commit_author:
      name: Tom Fleet
      email: me@followtheprocess.codes
    repository:
      owner: FollowTheProcess
      name: homebrew-tap
      token: "{{.Env.HOMEBREW_TAP_TOKEN}}"
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status.zero?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zap"]
          end

dockers_v2:
  - images:
      - followtheprocess/zap
      - ghcr.io/followtheprocess/zap
    tags:
      - "{{ .Version }}"
    labels:
      "org.opencontainers.image.description": "A command line .http file toolkit"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"

docker_digest:
  name_template: digests.txt
  disable: false

archives:
  - id: zap
    format_overrides:
      - goos: windows
        formats: zip
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

sboms:
  - id: zap
    artifacts: archive
    documents:
      - >-
        {{ .ProjectName }}-
        {{- .Version }}-
        {{- .Os }}-
        {{- if eq .Arch "amd64" }}x86_64
        {{- else if eq .Arch "386" }}i386
        {{- else }}{{ .Arch }}{{ end }}.sbom

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ .Tag }}-dev{{ .ShortCommit }}"

changelog:
  # The changelog is handled by release drafter
  disable: true
