// Code generated by "stringer -type Kind -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[Error-1]
	_ = x[Comment-2]
	_ = x[Separator-3]
	_ = x[At-4]
	_ = x[Ident-5]
	_ = x[Eq-6]
	_ = x[Colon-7]
	_ = x[LeftAngle-8]
	_ = x[RightAngle-9]
	_ = x[Text-10]
	_ = x[Body-11]
	_ = x[URL-12]
	_ = x[HTTPVersion-13]
	_ = x[Header-14]
	_ = x[OpenInterp-15]
	_ = x[CloseInterp-16]
	_ = x[Name-17]
	_ = x[Prompt-18]
	_ = x[Timeout-19]
	_ = x[ConnectionTimeout-20]
	_ = x[NoRedirect-21]
	_ = x[MethodGet-22]
	_ = x[MethodHead-23]
	_ = x[MethodPost-24]
	_ = x[MethodPut-25]
	_ = x[MethodDelete-26]
	_ = x[MethodConnect-27]
	_ = x[MethodPatch-28]
	_ = x[MethodOptions-29]
	_ = x[MethodTrace-30]
}

const _Kind_name = "EOFErrorCommentSeparatorAtIdentEqColonLeftAngleRightAngleTextBodyURLHTTPVersionHeaderOpenInterpCloseInterpNamePromptTimeoutConnectionTimeoutNoRedirectMethodGetMethodHeadMethodPostMethodPutMethodDeleteMethodConnectMethodPatchMethodOptionsMethodTrace"

var _Kind_index = [...]uint8{0, 3, 8, 15, 24, 26, 31, 33, 38, 47, 57, 61, 65, 68, 79, 85, 95, 106, 110, 116, 123, 140, 150, 159, 169, 179, 188, 200, 213, 224, 237, 248}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
