// Code generated by "stringer -type Kind -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[Error-1]
	_ = x[Comment-2]
	_ = x[Separator-3]
	_ = x[At-4]
	_ = x[Ident-5]
	_ = x[Eq-6]
	_ = x[Dollar-7]
	_ = x[Colon-8]
	_ = x[LeftAngle-9]
	_ = x[RightAngle-10]
	_ = x[ResponseRef-11]
	_ = x[Text-12]
	_ = x[Body-13]
	_ = x[HTTPVersion-14]
	_ = x[Header-15]
	_ = x[OpenInterp-16]
	_ = x[CloseInterp-17]
	_ = x[Name-18]
	_ = x[Prompt-19]
	_ = x[Timeout-20]
	_ = x[ConnectionTimeout-21]
	_ = x[NoRedirect-22]
	_ = x[MethodGet-23]
	_ = x[MethodHead-24]
	_ = x[MethodPost-25]
	_ = x[MethodPut-26]
	_ = x[MethodDelete-27]
	_ = x[MethodConnect-28]
	_ = x[MethodPatch-29]
	_ = x[MethodOptions-30]
	_ = x[MethodTrace-31]
}

const _Kind_name = "EOFErrorCommentSeparatorAtIdentEqDollarColonLeftAngleRightAngleResponseRefTextBodyHTTPVersionHeaderOpenInterpCloseInterpNamePromptTimeoutConnectionTimeoutNoRedirectMethodGetMethodHeadMethodPostMethodPutMethodDeleteMethodConnectMethodPatchMethodOptionsMethodTrace"

var _Kind_index = [...]uint16{0, 3, 8, 15, 24, 26, 31, 33, 39, 44, 53, 63, 74, 78, 82, 93, 99, 109, 120, 124, 130, 137, 154, 164, 173, 183, 193, 202, 214, 227, 238, 251, 262}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
